/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class calculatortest extends javax.swing.JFrame {

    /**
     * Creates new form calculatortest
     */
    public calculatortest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NUM1 = new javax.swing.JButton();
        APPNAME = new javax.swing.JLabel();
        NUM2 = new javax.swing.JButton();
        NUM4 = new javax.swing.JButton();
        NUM5 = new javax.swing.JButton();
        NUM3 = new javax.swing.JButton();
        NUM6 = new javax.swing.JButton();
        NUM7 = new javax.swing.JButton();
        NUM8 = new javax.swing.JButton();
        NUM9 = new javax.swing.JButton();
        NUM0 = new javax.swing.JButton();
        EQUALTO = new javax.swing.JButton();
        PLUS = new javax.swing.JButton();
        MINUS = new javax.swing.JButton();
        DIVIDE = new javax.swing.JButton();
        MULTIPLY = new javax.swing.JButton();
        EXPRESSION = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NUM1.setText("1");

        APPNAME.setText("CALCULATOR");
        APPNAME.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        NUM2.setText("2");
        NUM2.setName("NUM2"); // NOI18N

        NUM4.setText("4");

        NUM5.setText("5");

        NUM3.setText("3");

        NUM6.setText("6");

        NUM7.setText("7");

        NUM8.setText("8");

        NUM9.setText("9");

        NUM0.setText("0");

        EQUALTO.setText("=");

        PLUS.setText("+");

        MINUS.setText("-");

        DIVIDE.setText("/");

        MULTIPLY.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EXPRESSION, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(NUM0)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EQUALTO, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(MULTIPLY))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NUM1)
                                        .addGap(18, 18, 18)
                                        .addComponent(NUM2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NUM4)
                                        .addGap(18, 18, 18)
                                        .addComponent(NUM5)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NUM7)
                                    .addGap(18, 18, 18)
                                    .addComponent(NUM8)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NUM6)
                                    .addGap(18, 18, 18)
                                    .addComponent(MINUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NUM3)
                                    .addGap(18, 18, 18)
                                    .addComponent(PLUS))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NUM9)
                                    .addGap(18, 18, 18)
                                    .addComponent(DIVIDE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(APPNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(APPNAME)
                .addGap(11, 11, 11)
                .addComponent(EXPRESSION, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUM1)
                    .addComponent(NUM2)
                    .addComponent(NUM3)
                    .addComponent(PLUS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUM4)
                    .addComponent(NUM5)
                    .addComponent(NUM6)
                    .addComponent(MINUS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUM7)
                    .addComponent(NUM8)
                    .addComponent(NUM9)
                    .addComponent(DIVIDE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUM0)
                    .addComponent(EQUALTO)
                    .addComponent(MULTIPLY))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatortest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatortest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatortest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatortest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatortest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APPNAME;
    private javax.swing.JButton DIVIDE;
    private javax.swing.JButton EQUALTO;
    private javax.swing.JTextField EXPRESSION;
    private javax.swing.JButton MINUS;
    private javax.swing.JButton MULTIPLY;
    private javax.swing.JButton NUM0;
    private javax.swing.JButton NUM1;
    private javax.swing.JButton NUM2;
    private javax.swing.JButton NUM3;
    private javax.swing.JButton NUM4;
    private javax.swing.JButton NUM5;
    private javax.swing.JButton NUM6;
    private javax.swing.JButton NUM7;
    private javax.swing.JButton NUM8;
    private javax.swing.JButton NUM9;
    private javax.swing.JButton PLUS;
    // End of variables declaration//GEN-END:variables
}
